print(60 + float(100.55))
num=len(input("enter your name : "))
print("your name has ",num," charaters")
print(type(num))
new=str(num)
print("your name has " + new + " charaters")
print(type(new))